#!/bin/bash
# Test script demonstrating stdin support in rocketype
# These are example commands - they will launch rocketype in interactive mode

echo "=== Rocketype Stdin Support Test Examples ==="
echo ""
echo "1. Test with simple echo:"
echo "   echo 'The quick brown fox jumps over the lazy dog' | ./rocketype"
echo ""
echo "2. Test with cat from file:"
echo "   cat texts/pangrams.txt | ./rocketype"
echo ""
echo "3. Test with here-doc:"
echo "   cat <<EOF | ./rocketype"
echo "   This is a multi-line"
echo "   test of stdin support"
echo "   with rocketype!"
echo "   EOF"
echo ""
echo "4. Test with command output:"
echo "   ls -la | ./rocketype"
echo ""
echo "5. Test with curl (requires internet):"
echo "   curl -s https://www.gutenberg.org/files/1342/1342-0.txt | head -20 | ./rocketype"
echo ""
echo "Run any of the above commands to test stdin support."
